name: Generate pacman animation

on:
  schedule:
    - cron: "0 */12 * * *"    # chạy mỗi 12 giờ (0 phút của giờ chẵn)
  workflow_dispatch:           # cho phép chạy thủ công từ GitHub UI
  push:
    branches:
      - main                 # chạy khi có push nhánh main

jobs:
  generate:
    permissions:
      contents: write         # cho phép ghi file trên repo (đẩy nhánh output)
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0        # lấy toàn bộ lịch sử git, cần cho push

      - name: Generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      - name: Push generated SVG to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
